on:
  pull_request:
    types: [closed]
    branches:
      - main
    # Trigger the workflow only when the pull request is merged to main
    # and not when it's closed without merging
    # You can remove this condition to activate the workflow for both cases
    # if that's what you want
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request
    # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
    condition: ${{ github.event.pull_request.merged && github.event.pull_request.base.ref == 'main' }}
jobs:
  protect-main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: 'refs/heads/main'

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.0.9'

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: "0.14.0"
        tf_command: "init"
        working_directory: "./.github/terraform"

    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: "0.14.0"
        tf_command: "apply -auto-approve"
        working_directory: "./.github/terraform"
      env:
        GITHUB_TOKEN: ${{ secrets.BUILDBOUQUET_GITHUB_MANAGEMENT_TOKEN }}
