name: CI/CD

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Print pwd
        run: pwd
      - name: Print directory structure
        run: ls -laR
      - name: Print directory structure
        run: ls -la /home/runner/work/buildbouquet/buildbouquet/.github/workflows/terraform


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.9'
      - name: Terraform Plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: "0.14.0"
          tf_actions_subcommand: "plan"
          tf_actions_working_dir: /home/runner/work/buildbouquet/buildbouquet/.github/workflows/terraform
        env:
          GITHUB_TOKEN: ${{ secrets.BUILDBOUQUET_GITHUB_MANAGEMENT_TOKEN }}


  terraform-apply:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'refs/heads/main'
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.9'
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: "0.14.0"
          tf_actions_subcommand: "init"
          tf_actions_working_dir: /home/runner/work/buildbouquet/buildbouquet/.github/workflows/terraform
        env:
          GITHUB_TOKEN: ${{ secrets.BUILDBOUQUET_GITHUB_MANAGEMENT_TOKEN }}
      - name: Terraform Apply
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: "0.14.0"
          tf_actions_subcommand: "apply -auto-approve"
          tf_actions_working_dir: /home/runner/work/buildbouquet/buildbouquet/.github/workflows/terraform
        env:
          GITHUB_TOKEN: ${{ secrets.BUILDBOUQUET_GITHUB_MANAGEMENT_TOKEN }}
