name: branch-setup

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 16.x
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.9'
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: "1.0.9"
          tf_actions_subcommand: "init"
          tf_actions_working_dir: .github/terraform
        env:
          GITHUB_TOKEN: ${{ secrets.BUILDBOUQUET_GITHUB_MANAGEMENT_TOKEN }}
      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: "1.0.9"
          tf_actions_subcommand: "validate"
          tf_actions_working_dir: .github/terraform
        env:
          GITHUB_TOKEN: ${{ secrets.BUILDBOUQUET_GITHUB_MANAGEMENT_TOKEN }}
      - name: Terraform Plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: "1.0.9"
          tf_actions_subcommand: "plan"
          tf_actions_working_dir: .github/terraform
        env:
          GITHUB_TOKEN: ${{ secrets.BUILDBOUQUET_GITHUB_MANAGEMENT_TOKEN }}


  terraform-apply:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 16.x
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'refs/heads/main'
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.9'
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: "1.0.9"
          tf_actions_subcommand: "init"
          tf_actions_working_dir: .github/terraform
        env:
          GITHUB_TOKEN: ${{ secrets.BUILDBOUQUET_GITHUB_MANAGEMENT_TOKEN }}
      - name: Terraform Apply
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: "1.0.9"
          tf_actions_subcommand: "apply"
          tf_actions_working_dir: .github/terraform
        env:
          GITHUB_TOKEN: ${{ secrets.BUILDBOUQUET_GITHUB_MANAGEMENT_TOKEN }}


