name: Lint README

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint README.md
        run: |
          mdl README.md

    # Optional step to view the pip cache directory permissions for troubleshooting
    - name: Check pip cache directory permissions
      run: ls -ld ~/.cache/pip

    # Optional step to view the pip version for troubleshooting
    - name: Check pip version
      run: pip --version

    # Optional step to view the installed packages for troubleshooting
    - name: List installed packages
      run: pip list
