name: Lint README

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: python:3.9

    steps:
      - name: Check pip cache directory permissions
        run: |
          if [ -d ~/.cache/pip ]; then ls -ld ~/.cache/pip; else echo "Directory does not exist"; fi

      - name: Check pip version
        run: pip --version

      - name: List installed packages
        run: pip list

      - name: Search for package
        run: |
          pip search markdownlint
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Lint README.md
        run: |
          mdl README.md
