name: Lint Markdown Files

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main


jobs:
  markdownlint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/igorshubovych/markdownlint-cli:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint markdown files
        run: markdownlint **/*.md
