name: Lint README

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install --no-cache-dir pymarkdownlint

      - name: Lint README.md
        run: |
          pymarkdownlint README.md
