name: Lint README

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint README.md
        run: mdl README.md

      - name: Check pip cache directory permissions
        run: ls -ld ~/.cache/pip

      - name: Check pip version
        run: pip --version

      - name: List installed packages
        run: pip list
